### ISSUE TITLE
Suggested changes

### ISSUE THREAD

**Issue by PolinaStamenova** [swengineermwi/todo-review#2]
Good and clean logic.

- It would be good to dry DOM manipulation by using functions for creating several HTML elements and for setting several event listeners to the same elements.

- Make sure you removed all console.log from your code. 
- One more thing, change k++ => k += 1 , because of the linters 

- It would be nice to change how often your page reloads, as this can cause memory and response time issue for your client-sided project.

_Happy coding_ 😄

**Comment by swengineermwi** [comment]
Thanks, @PolinaStamenova for the constructive review. I'm on it.
